### ISSUE TITLE
CI script function is deprecated. 

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz-proto#14]
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/6308023/210451868-255162d6-cfe3-4ad2-b9a5-dc74ea7bd1af.png">

with old previous action it's been deprecated and it needs to be replaced any time soon.

**Comment by xellos00** [comment]
@kim201212 
Can you confirm this too? seems there's still some trouble with it. 
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/6308023/210496171-18df2c74-5391-4464-932b-6de1587d5170.png">

**Comment by kim201212** [comment]
@xellos00 
Please change `Protected branches` setting to unprotect

**Comment by xellos00** [comment]
@

> @xellos00 Please change `Protected branches` setting of `vatz-proto` repo to unprotect

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/6308023/222054724-32f8c178-6955-457d-9bcf-29e870c61762.png">

**Comment by kim201212** [comment]
Hold in the comments below.
- https://github.com/dsrvlabs/vatz/issues/87#issuecomment-1514119048
